# adding base image ubuntu
FROM ubuntu:latest
#adding maintainers of this docker
MAINTAINER Bogdan Myslyvchuk & Marian Mazurak

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y
